spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pillprompt?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jm00

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug

openai:
  model: "gpt-3.5-turbo"
  api:
    key: "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"
    url: "https://api.openai.com/v1/chat/completions"
